import {boardColors} from "styles"

export default {
  cities: {
    "flensburg": {posX: 497, posY: 41, color: boardColors.purple},
    "kiel": {posX: 529, posY: 150, color: boardColors.purple},
    "hamburg": {posX: 508, posY: 346, color: boardColors.purple},
    "cuxhaven": {posX: 395, posY: 228, color: boardColors.purple},
    "wilhelmshaven": {posX: 289, posY: 300, color: boardColors.purple},
    "bremen": {posX: 394, posY: 426, color: boardColors.purple},
    "hannover": {posX: 469, posY: 559, color: boardColors.purple},
    "lubeck": {posX: 589, posY: 229, color: boardColors.red},
    "schwerin": {posX: 669, posY: 329, color: boardColors.red},
    "rostock": {posX: 731, posY: 190, color: boardColors.red},
    "torgelow": {posX: 910, posY: 279, color: boardColors.red},
    "magdeberg": {posX: 694, posY: 562, color: boardColors.red},
    "berlin": {posX: 875, posY: 559, color: boardColors.red},
    "frankfurtO": {posX: 1003, posY: 623, color: boardColors.red},
    "osnabruck": {posX: 295, posY: 563, color: boardColors.blue},
    "munster": {posX: 261, posY: 680, color: boardColors.blue},
    "duisburg": {posX: 81, posY: 721, color: boardColors.blue},
    "essen": {posX: 202, posY: 752, color: boardColors.blue},
    "dortmund": {posX: 285, posY: 788, color: boardColors.blue},
    "kassel": {posX: 417, posY: 806, color: boardColors.blue},
    "dusseldorf": {posX: 177, posY: 865, color: boardColors.blue},
    "halle": {posX: 734, posY: 731, color: boardColors.pink},
    "leipzig": {posX: 767, posY: 824, color: boardColors.pink},
    "erfurt": {posX: 610, posY: 867, color: boardColors.pink},
    "dresden": {posX: 940, posY: 906, color: boardColors.pink},
    "fulda": {posX: 503, posY: 979, color: boardColors.pink},
    "wurzburg": {posX: 535, posY: 1167, color: boardColors.pink},
    "nurnburg": {posX: 634, posY: 1278, color: boardColors.pink},
    "aachen": {posX: 149, posY: 985, color: boardColors.orange},
    "koln": {posX: 249, posY: 960, color: boardColors.orange},
    "trier": {posX: 199, posY: 1199, color: boardColors.orange},
    "wiesbaden": {posX: 346, posY: 1119, color: boardColors.orange},
    "frankfurtM": {posX: 388, posY: 1031, color: boardColors.orange},
    "saarbrucken": {posX: 271, posY: 1271, color: boardColors.orange},
    "mannheim": {posX: 396, posY: 1263, color: boardColors.orange},
    "freiburg": {posX: 303, posY: 1505, color: boardColors.black},
    "stuttgart": {posX: 438, posY: 1458, color: boardColors.black},
    "konstanz": {posX: 422, posY: 1631, color: boardColors.black},
    "augsburg": {posX: 600, posY: 1488, color: boardColors.black},
    "regensberg": {posX: 722, posY: 1416, color: boardColors.black},
    "munchen": {posX: 693, posY: 1609, color: boardColors.black},
    "passau": {posX: 826, posY: 1552, color: boardColors.black}
  },
  tunnels: [
    {city1: "flensburg", city2: "kiel", price: 4},
    {city1: "kiel", city2: "hamburg", price: 8},
    {city1: "kiel", city2: "lubeck", price: 4},
    {city1: "hamburg", city2: "cuxhaven", price: 11},
    {city1: "hamburg", city2: "lubeck", price: 6},
    {city1: "hamburg", city2: "schwerin", price: 8},
    {city1: "hamburg", city2: "bremen", price: 11},
    {city1: "hamburg", city2: "hannover", price: 17},
    {city1: "cuxhaven", city2: "bremen", price: 8},
    {city1: "bremen", city2: "wilhelmshaven", price: 11},
    {city1: "bremen", city2: "hannover", price: 10},
    {city1: "wilhelmshaven", city2: "osnabruck", price: 14},
    {city1: "hannover", city2: "schwerin", price: 19},
    {city1: "hannover", city2: "magdeberg", price: 15},
    {city1: "hannover", city2: "erfurt", price: 19},
    {city1: "hannover", city2: "kassel", price: 15},
    {city1: "hannover", city2: "osnabruck", price: 16},
    {city1: "lubeck", city2: "schwerin", price: 6},
    {city1: "schwerin", city2: "rostock", price: 6},
    {city1: "schwerin", city2: "torgelow", price: 19},
    {city1: "schwerin", city2: "berlin", price: 18},
    {city1: "schwerin", city2: "magdeberg", price: 16},
    {city1: "rostock", city2: "torgelow", price: 19},
    {city1: "torgelow", city2: "berlin", price: 15},
    {city1: "magdeberg", city2: "berlin", price: 10},
    {city1: "magdeberg", city2: "halle", price: 11},
    {city1: "berlin", city2: "halle", price: 17},
    {city1: "berlin", city2: "frankfurtO", price: 6},
    {city1: "frankfurtO", city2: "leipzig", price: 21},
    {city1: "frankfurtO", city2: "dresden", price: 16},
    {city1: "osnabruck", city2: "munster", price: 7},
    {city1: "osnabruck", city2: "kassel", price: 20},
    {city1: "munster", city2: "essen", price: 6},
    {city1: "munster", city2: "dortmund", price: 2},
    {city1: "duisburg", city2: "essen", price: 0},
    {city1: "essen", city2: "dortmund", price: 4},
    {city1: "essen", city2: "dusseldorf", price: 2},
    {city1: "dortmund", city2: "kassel", price: 18},
    {city1: "dortmund", city2: "frankfurtM", price: 20},
    {city1: "dortmund", city2: "koln", price: 10},
    {city1: "dusseldorf", city2: "aachen", price: 9},
    {city1: "dusseldorf", city2: "koln", price: 4},
    {city1: "kassel", city2: "erfurt", price: 15},
    {city1: "kassel", city2: "fulda", price: 8},
    {city1: "kassel", city2: "frankfurtM", price: 13},
    {city1: "halle", city2: "leipzig", price: 0},
    {city1: "halle", city2: "erfurt", price: 6},
    {city1: "leipzig", city2: "dresden", price: 13},
    {city1: "dresden", city2: "erfurt", price: 19},
    {city1: "erfurt", city2: "fulda", price: 13},
    {city1: "erfurt", city2: "nurnburg", price: 21},
    {city1: "fulda", city2: "wurzburg", price: 11},
    {city1: "wurzburg", city2: "nurnburg", price: 8},
    {city1: "wurzburg", city2: "augsburg", price: 19},
    {city1: "wurzburg", city2: "stuttgart", price: 12},
    {city1: "nurnburg", city2: "augsburg", price: 18},
    {city1: "nurnburg", city2: "regensberg", price: 12},
    {city1: "aachen", city2: "koln", price: 7},
    {city1: "aachen", city2: "trier", price: 19},
    {city1: "koln", city2: "trier", price: 20},
    {city1: "koln", city2: "wiesbaden", price: 21},
    {city1: "trier", city2: "saarbrucken", price: 11},
    {city1: "wiesbaden", city2: "frankfurtM", price: 0},
    {city1: "wiesbaden", city2: "mannheim", price: 11},
    {city1: "wiesbaden", city2: "saarbrucken", price: 10},
    {city1: "frankfurtM", city2: "fulda", price: 8},
    {city1: "frankfurtM", city2: "wurzburg", price: 13},
    {city1: "saarbrucken", city2: "stuttgart", price: 17},
    {city1: "mannheim", city2: "stuttgart", price: 6},
    {city1: "mannheim", city2: "wurzburg", price: 10},
    {city1: "freiburg", city2: "stuttgart", price: 16},
    {city1: "freiburg", city2: "konstanz", price: 14},
    {city1: "stuttgart", city2: "augsburg", price: 15},
    {city1: "stuttgart", city2: "konstanz", price: 16},
    {city1: "konstanz", city2: "augsburg", price: 17},
    {city1: "augsburg", city2: "regensberg", price: 13},
    {city1: "augsburg", city2: "munchen", price: 6},
    {city1: "regensberg", city2: "munchen", price: 10},
    {city1: "regensberg", city2: "passau", price: 12},
    {city1: "munchen", city2: "passau", price: 14 }
  ]
}
