import {boardColors} from "styles"

const citiesInfo = {
  "seattle": {posX: 50, posY: 30, color: boardColors.purple},
  "portland": {posX: 25, posY: 130, color: boardColors.purple},
  "boise": {posX: 130, posY: 150, color: boardColors.purple},
  "billings": {posX: 220, posY: 110, color: boardColors.purple},
  "cheyenne": {posX: 240, posY: 200, color: boardColors.purple},
  "denver": {posX: 230, posY: 280, color: boardColors.purple},
  "omaha": {posX: 350, posY: 220, color: boardColors.purple},
  "fargo": {posX: 350, posY: 90, color: boardColors.red},
  "duluth": {posX: 430, posY: 10, color: boardColors.red},
  "minneapolis": {posX: 440, posY: 150, color: boardColors.red},
  "chicago": {posX: 620, posY: 190, color: boardColors.red},
  "st_louis": {posX: 580, posY: 290, color: boardColors.red},
  "cincinnati": {posX: 700, posY: 240, color: boardColors.red},
  "knoxville": {posX: 700, posY: 340, color: boardColors.red},
  "detroit": {posX: 700, posY: 130, color: boardColors.blue},
  "buffalo": {posX: 800, posY: 90, color: boardColors.blue},
  "pittsburgh": {posX: 800, posY: 190, color: boardColors.blue},
  "washington": {posX: 930, posY: 270, color: boardColors.blue},
  "philadelphia": {posX: 940, posY: 180, color: boardColors.blue},
  "new_york": {posX: 960, posY: 90, color: boardColors.blue},
  "boston": {posX: 980, posY: 0, color: boardColors.blue},
  "san_francisco": {posX: 0, posY: 480, color: boardColors.pink},
  "salt_lake_city": {posX: 150, posY: 400, color: boardColors.pink},
  "las_vegas": {posX: 150, posY: 500, color: boardColors.pink},
  "santa_fe": {posX: 270, posY: 520, color: boardColors.pink},
  "los_angeles": {posX: 20, posY: 600, color: boardColors.pink},
  "san_diego": {posX: 30, posY: 700, color: boardColors.pink},
  "phoenix": {posX: 200, posY: 650, color: boardColors.pink},
  "kansas_city": {posX: 400, posY: 340, color: boardColors.orange},
  "oklahoma_city": {posX: 380, posY: 440, color: boardColors.orange},
  "dallas": {posX: 400, posY: 540, color: boardColors.orange},
  "houston": {posX: 410, posY: 640, color: boardColors.orange},
  "memphis": {posX: 570, posY: 460, color: boardColors.orange},
  "new_orleans": {posX: 560, posY: 620, color: boardColors.orange},
  "birmingham": {posX: 650, posY: 540, color: boardColors.orange},
  "atlanta": {posX: 690, posY: 440, color: boardColors.black},
  "raleigh": {posX: 810, posY: 360, color: boardColors.black},
  "norfolk": {posX: 900, posY: 350, color: boardColors.black},
  "savannah": {posX: 780, posY: 480, color: boardColors.black},
  "jacksonville": {posX: 800, posY: 570, color: boardColors.black},
  "tampa": {posX: 750, posY: 670, color: boardColors.black},
  "miami": {posX: 840, posY: 730, color: boardColors.black},
}

const cityTunnels = [
  {city1: "seattle", city2: "portland", price: "3"},
  {city1: "seattle", city2: "boise", price: "12"},
  {city1: "seattle", city2: "billings", price: "9"},
  {city1: "portland", city2: "boise", price: "13"},
  {city1: "portland", city2: "san_francisco", price: "24"},
  {city1: "boise", city2: "san_francisco", price: "23"},
  {city1: "boise", city2: "salt_lake_city", price: "8"},
  {city1: "boise", city2: "denver", price: "24"},
  {city1: "boise", city2: "billings", price: "12"},
  {city1: "billings", city2: "fargo", price: "17"},
  {city1: "billings", city2: "minneapolis", price: "18"},
  {city1: "billings", city2: "cheyenne", price: "9"},
  {city1: "cheyenne", city2: "minneapolis", price: "18"},
  {city1: "cheyenne", city2: "omaha", price: "14"},
  {city1: "cheyenne", city2: "denver", price: "0"},
  {city1: "denver", city2: "salt_lake_city", price: "21"},
  {city1: "denver", city2: "santa_fe", price: "13"},
  {city1: "denver", city2: "kansas_city", price: "16"},
  {city1: "omaha", city2: "minneapolis", price: "8"},
  {city1: "omaha", city2: "chicago", price: "13"},
  {city1: "omaha", city2: "kansas_city", price: "5"},
  {city1: "san_francisco", city2: "salt_lake_city", price: "27"},
  {city1: "san_francisco", city2: "las_vegas", price: "14"},
  {city1: "san_francisco", city2: "los_angeles", price: "9"},
  {city1: "los_angeles", city2: "las_vegas", price: "9"},
  {city1: "los_angeles", city2: "san_diego", price: "3"},
  {city1: "san_diego", city2: "las_vegas", price: "9"},
  {city1: "san_diego", city2: "phoenix", price: "14"},
  {city1: "las_vegas", city2: "salt_lake_city", price: "18"},
  {city1: "las_vegas", city2: "santa_fe", price: "27"},
  {city1: "las_vegas", city2: "phoenix", price: "15"},
  {city1: "phoenix", city2: "santa_fe", price: "18"},
  {city1: "salt_lake_city", city2: "santa_fe", price: "28"},
  {city1: "santa_fe", city2: "kansas_city", price: "16"},
  {city1: "santa_fe", city2: "oklahoma_city", price: "15"},
  {city1: "santa_fe", city2: "dallas", price: "16"},
  {city1: "santa_fe", city2: "houston", price: "21"},
  {city1: "fargo", city2: "duluth", price: "6"},
  {city1: "fargo", city2: "minneapolis", price: "6"},
  {city1: "duluth", city2: "minneapolis", price: "5"},
  {city1: "duluth", city2: "detroit", price: "15"},
  {city1: "duluth", city2: "chicago", price: "12"},
  {city1: "minneapolis", city2: "chicago", price: "8"},
  {city1: "chicago", city2: "kansas_city", price: "8"},
  {city1: "chicago", city2: "st_louis", price: "10"},
  {city1: "chicago", city2: "cincinnati", price: "7"},
  {city1: "chicago", city2: "detroit", price: "7"},
  {city1: "st_louis", city2: "kansas_city", price: "6"},
  {city1: "st_louis", city2: "memphis", price: "7"},
  {city1: "st_louis", city2: "atlanta", price: "12"},
  {city1: "st_louis", city2: "cincinnati", price: "12"},
  {city1: "cincinnati", city2: "detroit", price: "4"},
  {city1: "cincinnati", city2: "pittsburgh", price: "7"},
  {city1: "cincinnati", city2: "raleigh", price: "15"},
  {city1: "cincinnati", city2: "knoxville", price: "6"},
  {city1: "knoxville", city2: "atlanta", price: "5"},
  {city1: "kansas_city", city2: "oklahoma_city", price: "8"},
  {city1: "kansas_city", city2: "memphis", price: "12"},
  {city1: "oklahoma_city", city2: "memphis", price: "14"},
  {city1: "oklahoma_city", city2: "dallas", price: "3"},
  {city1: "dallas", city2: "memphis", price: "12"},
  {city1: "dallas", city2: "houston", price: "5"},
  {city1: "dallas", city2: "new_orleans", price: "12"},
  {city1: "houston", city2: "new_orleans", price: "8"},
  {city1: "memphis", city2: "birmingham", price: "6"},
  {city1: "memphis", city2: "new_orleans", price: "7"},
  {city1: "new_orleans", city2: "birmingham", price: "11"},
  {city1: "new_orleans", city2: "jacksonville", price: "16"},
  {city1: "birmingham", city2: "atlanta", price: "3"},
  {city1: "birmingham", city2: "jacksonville", price: "9"},
  {city1: "detroit", city2: "buffalo", price: "7"},
  {city1: "detroit", city2: "pittsburgh", price: "6"},
  {city1: "buffalo", city2: "pittsburgh", price: "7"},
  {city1: "buffalo", city2: "new_york", price: "8"},
  {city1: "pittsburgh", city2: "washington", price: "6"},
  {city1: "pittsburgh", city2: "raleigh", price: "7"},
  {city1: "washington", city2: "philadelphia", price: "3"},
  {city1: "washington", city2: "norfolk", price: "5"},
  {city1: "philadelphia", city2: "new_york", price: "0"},
  {city1: "new_york", city2: "boston", price: "3"},
  {city1: "atlanta", city2: "raleigh", price: "7"},
  {city1: "atlanta", city2: "savannah", price: "7"},
  {city1: "norfolk", city2: "raleigh", price: "3"},
  {city1: "raleigh", city2: "savannah", price: "7"},
  {city1: "savannah", city2: "jacksonville", price: "0"},
  {city1: "jacksonville", city2: "tampa", price: "4"},
  {city1: "tampa", city2: "miami", price: "4"}
]

export {citiesInfo, cityTunnels}
