const plants = [
  null,
  null,
  null,
  {resourceAmountNeeded: 2, plantType: "oil", supportCityAmount: 1},
  {resourceAmountNeeded: 2, plantType: "coal", supportCityAmount: 1},
  {resourceAmountNeeded: 2, plantType: "hybrid", supportCityAmount: 1},
  {resourceAmountNeeded: 2, plantType: "garbage", supportCityAmount: 1},
  {resourceAmountNeeded: 3, plantType: "oil", supportCityAmount: 2},
  {resourceAmountNeeded: 3, plantType: "coal", supportCityAmount: 2},
  {resourceAmountNeeded: 1, plantType: "oil", supportCityAmount: 1},
  {resourceAmountNeeded: 2, plantType: "coal", supportCityAmount: 2},
  {resourceAmountNeeded: 1, plantType: "uranium", supportCityAmount: 2},
  {resourceAmountNeeded: 2, plantType: "hybrid", supportCityAmount: 2},
  {resourceAmountNeeded: 0, plantType: "wind", supportCityAmount: 1},
  {resourceAmountNeeded: 2, plantType: "garbage", supportCityAmount: 2},
  {resourceAmountNeeded: 2, plantType: "coal", supportCityAmount: 3},
  {resourceAmountNeeded: 2, plantType: "oil", supportCityAmount: 3},
  {resourceAmountNeeded: 1, plantType: "uranium", supportCityAmount: 2},
  {resourceAmountNeeded: 0, plantType: "wind", supportCityAmount: 2},
  {resourceAmountNeeded: 2, plantType: "garbage", supportCityAmount: 3},
  {resourceAmountNeeded: 3, plantType: "coal", supportCityAmount: 5},
  {resourceAmountNeeded: 2, plantType: "hybrid", supportCityAmount: 4},
  {resourceAmountNeeded: 0, plantType: "wind", supportCityAmount: 2},
  {resourceAmountNeeded: 1, plantType: "uranium", supportCityAmount: 3},
  {resourceAmountNeeded: 2, plantType: "garbage", supportCityAmount: 4},
  {resourceAmountNeeded: 2, plantType: "coal", supportCityAmount: 5},
  {resourceAmountNeeded: 2, plantType: "oil", supportCityAmount: 5},
  {resourceAmountNeeded: 0, plantType: "wind", supportCityAmount: 3},
  {resourceAmountNeeded: 1, plantType: "uranium", supportCityAmount: 4},
  {resourceAmountNeeded: 1, plantType: "hybrid", supportCityAmount: 4},
  {resourceAmountNeeded: 3, plantType: "garbage", supportCityAmount: 6},
  {resourceAmountNeeded: 3, plantType: "coal", supportCityAmount: 6},
  {resourceAmountNeeded: 3, plantType: "oil", supportCityAmount: 6},
  {resourceAmountNeeded: 0, plantType: "wind", supportCityAmount: 4},
  {resourceAmountNeeded: 1, plantType: "uranium", supportCityAmount: 5},
  {resourceAmountNeeded: 1, plantType: "oil", supportCityAmount: 5},
  {resourceAmountNeeded: 3, plantType: "coal", supportCityAmount: 7},
  {resourceAmountNeeded: 0, plantType: "wind", supportCityAmount: 4},
  {resourceAmountNeeded: 3, plantType: "garbage", supportCityAmount: 7},
  {resourceAmountNeeded: 1, plantType: "uranium", supportCityAmount: 6},
  {resourceAmountNeeded: 2, plantType: "oil", supportCityAmount: 6},
  {resourceAmountNeeded: 2, plantType: "coal", supportCityAmount: 6},
  {resourceAmountNeeded: 0, plantType: "wind", supportCityAmount: 5},
  {resourceAmountNeeded: 3, plantType: "hybrid", supportCityAmount: 7},
  {resourceAmountNeeded: 0, plantType: "wind", supportCityAmount: 6}
]

export default plants
