const plants = {
  "03": {resourceAmountNeeded: 2, plantType: "oil", supportCityAmount: 1},
  "04": {resourceAmountNeeded: 2, plantType: "coal", supportCityAmount: 1},
  "05": {resourceAmountNeeded: 2, plantType: "hybrid", supportCityAmount: 1},
  "06": {resourceAmountNeeded: 2, plantType: "garbage", supportCityAmount: 1},
  "07": {resourceAmountNeeded: 3, plantType: "oil", supportCityAmount: 2},
  "08": {resourceAmountNeeded: 3, plantType: "coal", supportCityAmount: 2},
  "09": {resourceAmountNeeded: 1, plantType: "oil", supportCityAmount: 1},
  "10": {resourceAmountNeeded: 2, plantType: "coal", supportCityAmount: 2},
  "11": {resourceAmountNeeded: 1, plantType: "uranium", supportCityAmount: 2},
  "12": {resourceAmountNeeded: 2, plantType: "hybrid", supportCityAmount: 2},
  "13": {resourceAmountNeeded: 0, plantType: "ecological", supportCityAmount: 1},
  "14": {resourceAmountNeeded: 2, plantType: "garbage", supportCityAmount: 2},
  "15": {resourceAmountNeeded: 2, plantType: "coal", supportCityAmount: 3},
  "16": {resourceAmountNeeded: 2, plantType: "oil", supportCityAmount: 3},
  "17": {resourceAmountNeeded: 1, plantType: "uranium", supportCityAmount: 2},
  "18": {resourceAmountNeeded: 0, plantType: "ecological", supportCityAmount: 2},
  "19": {resourceAmountNeeded: 2, plantType: "garbage", supportCityAmount: 3},
  "20": {resourceAmountNeeded: 3, plantType: "coal", supportCityAmount: 5},
  "21": {resourceAmountNeeded: 2, plantType: "hybrid", supportCityAmount: 4},
  "22": {resourceAmountNeeded: 0, plantType: "ecological", supportCityAmount: 2},
  "23": {resourceAmountNeeded: 1, plantType: "uranium", supportCityAmount: 3},
  "24": {resourceAmountNeeded: 2, plantType: "garbage", supportCityAmount: 4},
  "25": {resourceAmountNeeded: 2, plantType: "coal", supportCityAmount: 5},
  "26": {resourceAmountNeeded: 2, plantType: "oil", supportCityAmount: 5},
  "27": {resourceAmountNeeded: 0, plantType: "ecological", supportCityAmount: 3},
  "28": {resourceAmountNeeded: 1, plantType: "uranium", supportCityAmount: 4},
  "29": {resourceAmountNeeded: 1, plantType: "hybrid", supportCityAmount: 4},
  "30": {resourceAmountNeeded: 3, plantType: "garbage", supportCityAmount: 6},
  "31": {resourceAmountNeeded: 3, plantType: "coal", supportCityAmount: 6},
  "32": {resourceAmountNeeded: 3, plantType: "oil", supportCityAmount: 6},
  "33": {resourceAmountNeeded: 0, plantType: "ecological", supportCityAmount: 4},
  "34": {resourceAmountNeeded: 1, plantType: "uranium", supportCityAmount: 5},
  "35": {resourceAmountNeeded: 1, plantType: "oil", supportCityAmount: 5},
  "36": {resourceAmountNeeded: 3, plantType: "coal", supportCityAmount: 7},
  "37": {resourceAmountNeeded: 0, plantType: "ecological", supportCityAmount: 4},
  "38": {resourceAmountNeeded: 3, plantType: "garbage", supportCityAmount: 7},
  "39": {resourceAmountNeeded: 1, plantType: "uranium", supportCityAmount: 6},
  "40": {resourceAmountNeeded: 2, plantType: "oil", supportCityAmount: 6},
  "42": {resourceAmountNeeded: 2, plantType: "coal", supportCityAmount: 6},
  "44": {resourceAmountNeeded: 0, plantType: "ecological", supportCityAmount: 5},
  "46": {resourceAmountNeeded: 3, plantType: "hybrid", supportCityAmount: 7},
  "50": {resourceAmountNeeded: 0, plantType: "ecological", supportCityAmount: 6},
  "step3": {plantType: "step3"}
}

export default plants
